version: '3'
services:
  postgres_db:
    image: 'postgres'
    container_name: 'pg_db2'
    ports:
    - "543:543"
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
  app_snk:
    build: ./
    container_name: 'sneaker'
    ports:
      - "8080:3033"
    environment:
     - POSTGRES_HOST=postgres_db
    volumes:
      - ./uploads
    restart: always