version: '3'
services:
  postgresdb:
    image: 'postgres'
    container_name: 'java-postgres'
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    restart: always
  app:
    build: ./
    container_name: 'java-app'
    ports:
      - "8080:8080"
    environment:
     - POSTGRES_HOST=postgresdb
    restart: always