version: '3'
services:
  postgresdb:
    image: 'postgres'
    container_name: 'java-postgres'
    ports:
    - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
  app:
    build: ./
    container_name: 'java-app'
    ports:
      - "3000:3000"
    environment:
     - POSTGRES_HOST=postgresdb
    restart: always